/// Converts a UUID into a memorable three-word label ID.
///
/// Format: `golden-mossy-hearth`  (adjective–adjective–noun)
/// Cardinality: 100 × 100 × 100 = 1,000,000 unique combos.
/// Deterministic: the same UUID always produces the same label.
/// The UUID is still stored in the database; this is display-only.
library;

/// Returns a cozy three-word label for [uuid], e.g. `"warm-faded-kettle"`.
String labelId(String uuid) {
  // Normalise: strip dashes, keep only hex digits, pad to at least 24 chars.
  final hex = uuid
      .replaceAll('-', '')
      .replaceAll(RegExp(r'[^0-9a-fA-F]'), '0')
      .padRight(24, '0');
  // Use three independent 8-hex-char windows (32 bits each).
  final i1 = int.parse(hex.substring(0, 8), radix: 16) % 100;
  final i2 = int.parse(hex.substring(8, 16), radix: 16) % 100;
  final i3 = int.parse(hex.substring(16, 24), radix: 16) % 100;
  return '${_adj[i1]}-${_adj[i2]}-${_nouns[i3]}';
}

// ── 100 cozy adjectives ───────────────────────────────────────────────────

const List<String> _adj = [
  'amber',
  'ancient',
  'ashen',
  'bare',
  'birch',
  'blanched',
  'blushed',
  'brass',
  'brewed',
  'calm',
  'candied',
  'cedar',
  'chalky',
  'chipped',
  'clay',
  'cloudy',
  'copper',
  'cozy',
  'cracked',
  'creamy',
  'crisp',
  'curled',
  'dawn',
  'dewy',
  'dim',
  'dusty',
  'earthy',
  'faded',
  'felted',
  'foggy',
  'frosted',
  'gathered',
  'gentle',
  'gilded',
  'glazed',
  'golden',
  'grainy',
  'grey',
  'heathered',
  'hewn',
  'honeyed',
  'hushed',
  'inky',
  'ivory',
  'knitted',
  'lacquered',
  'linen',
  'loamy',
  'low',
  'mellow',
  'misty',
  'mossy',
  'muted',
  'narrow',
  'nicked',
  'nodding',
  'oaken',
  'oiled',
  'old',
  'patched',
  'peaty',
  'pewter',
  'pilled',
  'pined',
  'pressed',
  'quiet',
  'raw',
  'rested',
  'ringed',
  'rosy',
  'rough',
  'rounded',
  'rubbed',
  'ruddy',
  'rugged',
  'russet',
  'salted',
  'sandy',
  'settled',
  'shaded',
  'shaggy',
  'silken',
  'smoked',
  'smooth',
  'soft',
  'sooty',
  'speckled',
  'still',
  'stony',
  'tallow',
  'toasted',
  'tumbled',
  'twisted',
  'warm',
  'washed',
  'waxed',
  'weathered',
  'wicker',
  'worn',
  'woven',
];

// ── 100 cozy nouns (domestic objects & materials) ─────────────────────────

const List<String> _nouns = [
  'acorn',
  'apron',
  'atlas',
  'awl',
  'basin',
  'basket',
  'beam',
  'bellows',
  'biscuit',
  'blanket',
  'bottle',
  'bowl',
  'brick',
  'broom',
  'brush',
  'bucket',
  'bundle',
  'button',
  'candle',
  'cask',
  'cellar',
  'chair',
  'chest',
  'chisel',
  'cloth',
  'coat',
  'comb',
  'cord',
  'corner',
  'crate',
  'crock',
  'cupboard',
  'curtain',
  'cushion',
  'drawer',
  'ember',
  'fence',
  'flask',
  'flax',
  'frame',
  'gate',
  'grate',
  'handle',
  'hearth',
  'hedge',
  'hinge',
  'hook',
  'jar',
  'jug',
  'kettle',
  'key',
  'knob',
  'ladder',
  'lamp',
  'latch',
  'linen',
  'loft',
  'log',
  'mantle',
  'mat',
  'mop',
  'mortar',
  'needle',
  'nook',
  'pail',
  'pantry',
  'patch',
  'pillow',
  'pipe',
  'plate',
  'pot',
  'press',
  'quilt',
  'rack',
  'rafter',
  'reel',
  'rope',
  'satchel',
  'settle',
  'shelf',
  'shutter',
  'sill',
  'skillet',
  'slate',
  'spool',
  'step',
  'stool',
  'stove',
  'thatch',
  'timber',
  'tinder',
  'tray',
  'urn',
  'vat',
  'vessel',
  'whetstone',
  'wick',
  'window',
  'wreath',
  'yoke',
];
