/// Maps ML Kit's generic image labels ("Chair", "Laptop") onto StillLife's
/// item categories. Coverage is intentionally the common-household subset —
/// anything unmapped falls to 'Other', never a guess. Keys are lowercase.
const Map<String, String> kMlKitLabelCategories = {
  // Electronics
  'laptop': 'Electronics',
  'computer': 'Electronics',
  'computer keyboard': 'Electronics',
  'computer monitor': 'Electronics',
  'television': 'Electronics',
  'camera': 'Electronics',
  'headphones': 'Electronics',
  'loudspeaker': 'Electronics',
  'smartphone': 'Electronics',
  'mobile phone': 'Electronics',
  'tablet computer': 'Electronics',
  'printer': 'Electronics',
  'remote control': 'Electronics',
  'video game console': 'Electronics',
  'keyboard': 'Electronics', // bare "keyboard" ≈ computer keyboard
  // Furniture
  'chair': 'Furniture',
  'couch': 'Furniture',
  'sofa': 'Furniture',
  'table': 'Furniture',
  'desk': 'Furniture',
  'bed': 'Furniture',
  'shelf': 'Furniture',
  'bookcase': 'Furniture',
  'cupboard': 'Furniture',
  'wardrobe': 'Furniture',
  'drawer': 'Furniture',
  'bench': 'Furniture',
  'stool': 'Furniture',
  'furniture': 'Furniture',
  // Appliances
  'refrigerator': 'Appliance',
  'oven': 'Appliance',
  'microwave oven': 'Appliance',
  'washing machine': 'Appliance',
  'dishwasher': 'Appliance',
  'vacuum cleaner': 'Appliance',
  'toaster': 'Appliance',
  'blender': 'Appliance',
  'mixer': 'Appliance',
  'kettle': 'Appliance',
  'coffeemaker': 'Appliance',
  'fan': 'Appliance',
  'air conditioning': 'Appliance',
  'home appliance': 'Appliance',
  // Clothing
  'clothing': 'Clothing',
  'jeans': 'Clothing',
  'dress': 'Clothing',
  'shirt': 'Clothing',
  't-shirt': 'Clothing',
  'jacket': 'Clothing',
  'coat': 'Clothing',
  'shoe': 'Clothing',
  'sneakers': 'Clothing',
  'boot': 'Clothing',
  'hat': 'Clothing',
  'cap': 'Clothing',
  'scarf': 'Clothing',
  'glove': 'Clothing',
  'sock': 'Clothing',
  'handbag': 'Clothing',
  'backpack': 'Clothing',
  // Kitchenware
  'mug': 'Kitchenware',
  'cup': 'Kitchenware',
  'glass': 'Kitchenware',
  'plate': 'Kitchenware',
  'bowl': 'Kitchenware',
  'tableware': 'Kitchenware',
  'cutlery': 'Kitchenware',
  'cookware': 'Kitchenware',
  'cookware and bakeware': 'Kitchenware',
  'frying pan': 'Kitchenware',
  'pot': 'Kitchenware',
  'jug': 'Kitchenware',
  'teapot': 'Kitchenware',
  // Decor
  'vase': 'Decor',
  'candle': 'Decor',
  'picture frame': 'Decor',
  'mirror': 'Decor',
  'lamp': 'Decor',
  'lampshade': 'Decor',
  'curtain': 'Decor',
  'pillow': 'Decor',
  'cushion': 'Decor',
  'rug': 'Decor',
  'clock': 'Decor',
  'flowerpot': 'Decor',
  'houseplant': 'Decor',
  // Tools
  'drill': 'Tool',
  'hammer': 'Tool',
  'screwdriver': 'Tool',
  'wrench': 'Tool',
  'saw': 'Tool',
  'pliers': 'Tool',
  'tool': 'Tool',
  'toolbox': 'Tool',
  'ladder': 'Tool',
  'tape measure': 'Tool',
  // Books
  'book': 'Book',
  'publication': 'Book',
  'magazine': 'Book',
  // Toys
  'toy': 'Toy',
  'doll': 'Toy',
  'teddy bear': 'Toy',
  'lego': 'Toy',
  'puzzle': 'Toy',
  'board game': 'Toy',
  // Sporting goods
  'bicycle': 'Sporting Goods',
  'skateboard': 'Sporting Goods',
  'ball': 'Sporting Goods',
  'football': 'Sporting Goods',
  'basketball': 'Sporting Goods',
  'tennis racket': 'Sporting Goods',
  'golf club': 'Sporting Goods',
  'ski': 'Sporting Goods',
  'surfboard': 'Sporting Goods',
  'dumbbell': 'Sporting Goods',
  'helmet': 'Sporting Goods',
  'tent': 'Sporting Goods',
  'fishing rod': 'Sporting Goods',
  // Jewelry
  'jewellery': 'Jewelry',
  'jewelry': 'Jewelry',
  'necklace': 'Jewelry',
  'ring': 'Jewelry',
  'bracelet': 'Jewelry',
  'earrings': 'Jewelry',
  'watch': 'Jewelry',
  // Art
  'painting': 'Art',
  'sculpture': 'Art',
  'drawing': 'Art',
  'art': 'Art',
  'poster': 'Art',
  // Musical instruments
  'guitar': 'Musical Instrument',
  'piano': 'Musical Instrument',
  'violin': 'Musical Instrument',
  'drum': 'Musical Instrument',
  'flute': 'Musical Instrument',
  'trumpet': 'Musical Instrument',
  'musical keyboard': 'Musical Instrument',
  'musical instrument': 'Musical Instrument',
};

/// StillLife category for an ML Kit label; 'Other' when unmapped.
String categoryForMlKitLabel(String label) =>
    kMlKitLabelCategories[label.toLowerCase()] ?? 'Other';
