# ── Flutter plugin framework ──────────────────────────────────────────────────
# Keep all Flutter engine and plugin registry classes so R8 does not strip the
# plugin registrar generated by flutter_tools.  Without these rules the
# platform-channel registration in onAttachedToEngine is silently lost at
# runtime, producing "Unable to establish connection on channel" errors.
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-dontwarn io.flutter.embedding.**

# ── Flutter / google_mlkit_text_recognition ───────────────────────────────────
# Ships a plugin that references optional non-Latin-script recogniser classes
# (Chinese, Devanagari, Japanese, Korean) and an optional TensorFlow Lite GPU
# delegate.  We only use Latin/English OCR, so these classes are never
# instantiated at runtime.  Suppress R8 missing-class errors.
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions
-dontwarn org.tensorflow.lite.gpu.GpuDelegateFactory$Options

# ── ffmpeg_kit_flutter_new ────────────────────────────────────────────────────
# The plugin ships keep rules but never declares them as consumer rules, so R8
# renamed its classes. Its JNI_OnLoad then cannot find them and throws a
# java.lang.Error while plugins are registered; that aborts registration of
# every plugin after it (share-to-Still-Life went dead with it). Found by
# booting the release APK on the emulator, October 2026.
-keep class com.antonkarpenko.ffmpegkit.** { *; }
-dontwarn com.antonkarpenko.ffmpegkit.**
-keepclasseswithmembernames class * {
    native <methods>;
}
